# Considerações {#sec-consideracoes}

A Ouvidoria da Senappen tem buscado atuar como instância de controle e participação social responsável pelo tratamento das solicitações, reclamações, denúncias, sugestões e elogios relativos às políticas e aos serviços públicos prestados por servidores e órgãos de administração da execução penal, sob qualquer forma ou regime. Neste sentido faz-se necessário compreender os serviços penais a partir de uma concepção ampla, definidas em [@alemPrisao] como um conjunto de ações e estruturas que envolvem equipamentos, políticas públicas, procedimentos e corpo técnico para acompanhamento das alternativas penais, monitoração eletrônica, medidas privativas de liberdade em qualquer regime e de atenção à pessoa egressa do sistema prisional.

Por essa razão, a Onasp buscou por meio dos projetos desenvolvidos, como o Ressocializa, o (Re)integro e a padronização de um formulário eletrônico de inspeção prisional (FIP) fortalecer arranjos institucionais entre diferentes órgãos, como forma de dar vazão à tecnologias sociais inovadoras, criando formas diversas de intervenção e de envolvimento do público e sociedade civil organizada. Além do tratamento das demandas encaminhadas, em sua quase totalidade por meio de correspondências físicas (cartas), as quais são registradas no Sistema Fala.BR e encaminhadas a órgãos externos em todo o território nacional, como Varas de Execução Penal, Ministérios Públicos, Defensorias Públicas e secretarias estaduais, responsáveis pela gestão penitenciária, a Onasp realiza ainda inspeções a estabelecimentos penais.

As atividades de inspeção tem como propósito verificar a estrutura preditiva, a oferta dos serviços relacionados às assistências previstas na Lei de Execução Penal, com especial atenção à oferta de assistência material às pessoas privadas de liberdade e os atendimentos jurídicos, de saúde, atividades educacionais, laborativas, sociais e religiosas. Os procedimentos incluem ainda verificações com a escuta às pessoas privadas de liberdade, servidores e gestores públicos. Como resultado é elaborado um relatório de inspeção, com avaliação dos serviços ofertados e as condições de custódia observadas no momento da visita, culminando em um conjunto de recomendações direcionadas aos órgãos e instituições que integram o subsistema de execução penal e que possuem atribuições e competências no âmbito do sistema prisional.

Para consolidar-se como uma instância de participação e controle social, a atuação da Ouvidoria demanda articulações interinstitucionais, junto a órgãos públicos, movimentos e organizações da sociedade civil que atuam com a temática de execução penal, o que requer entre outras atividades, a realização de eventos temáticos e deslocamentos para unidades federativas.\
Iniciado em meados de 2020, a Ouvidoria implantou um sistema de mapeamento das manifestações que recebe, tendo em vista as particularidades que caracterizam a principal forma como são recebidas (cartas físicas), cujos conteúdos materializam a realidade do sistema prisional, a partir dos relatos manuscritos e das narrativas apresentadas que envolvem uma gama de pedidos, solicitações, reclamações e denúncias, não raramente apresentadas de maneira conjunta em uma única correspondência, com mais de um manifestante. A ideia do mapeamento é lançar luz sobre as demandas de seus remetentes, pessoas privadas de liberdade cujo acesso à comunicação externa é restrito, suscetível a limitações burocráticas e a protocolos de segurança, não sendo possível acesso a canais eletrônicos de qualquer natureza.

Com adoção de fluxos desde o recebimento das cartas pelos serviços postais, é possível estabelecer dinâmicas que envolvam a sensibilização da equipe quanto ao tratamento a ser dado e a identificação de construtos relacionados às principais necessidades e reivindicações do ambiente prisional, tais como denúncias de tortura, violência, maus tratos, pedidos de assistência jurídica, solicitação de tratamentos de saúde, reclamações quanto as condições de custódia, ausência de oferta de serviços de educação e atividades laborativas, relatos de familiares sujeitos a tratamento degradante, entre outros. Acredita-se que as informações advindas dos dados coletados poderão auxiliar na construção de diagnósticos mais precisos sobre as condições dos estabelecimentos penais, as assistências com maior precariedade de provisão, as principais denúncias relacionadas a violações de direitos e os maiores déficits na oferta de políticas públicas no sistema prisional. Conhecimentos estes que objetivam apoiar as futuras tomadas de decisão e a formulação de projetos e políticas públicas para o aprimoramento da gestão penitenciária.

A perspectiva é avançar no processo de criação e fortalecimento das Ouvidorias penitenciárias estaduais, por meio de investimentos voltados para o aparelhamento de suas estruturas e a doação de veículos que permitam melhor capilaridade na realização de inspeções, em estabelecimentos penais sediados em suas regiões, com maior regularidade e padronização.

Uma das medidas em estudo na Onasp é impulsionar as ouvidorias penitenciárias, já existentes e que serão beneficiadas com recursos da Senappen, a realizarem a integração com o Fala.BR, ampliando a resolutividade e celeridade no tratamento e atendimento dos usuários, além de maior segurança nas ferramentas de comunicação e gerenciamento das demandas [@atlas].

Apesar dos desafios e o cenário de precariedade vivenciados no sistema prisional, entendemos que o trabalho da Ouvidoria Nacional dos Serviços Penais é instrumento de apoio à governança pública, com foco na participação e controle social, para o aprimoramento, dentro de seus limites de atuação, dos serviços penais e os principais propósitos da Lei de Execução Penal.

## Referências {.unnumbered}
