# Introdução {.unnumbered}

```{r}
vetor_filtro1 <- c(2020,2021,2022)
```

A elaboração do relatório de Gestão da Ouvidoria Nacional dos Serviços Penais busca efetivar as disposições contidas na lei nº 13.460/2017, que instituiu o Código de Defesa dos Usuários de Serviços Públicos e nas determinações estabelecidas na Portaria nº 581 de 09 de março de 2021, do Ministério da Transparência e Controladoria-Geral da União (CGU), que estabeleceu orientações para o exercício das competências das unidades do Sistema de Ouvidoria do Poder Executivo Federal, entre estas a necessidade de elaboração do Relatório Anual de Gestão por todas as Unidades do SisOuv.

Este relatório contempla informações no período de referência, ou seja, entre `r min(vetor_filtro1)` e `r max(vetor_filtro1)`. Estruturalmente, está organizado em três áreas de atuação, sendo: projetos capitaneados pela Onasp; ações da Ouvidoria Nacional dos Serviços Penais; e tratamentos estatísticos das demandas de ouvidoria.

O [capítulo @sec-projetos] trata dos projetos desenvolvidos pela Onasp com o objetivo de fomentar e apoiar formas de participação social no planejamento, elaboração, fiscalização e controle de propostas, políticas públicas e ações institucionais no âmbito da execução penal. Nesse sentido, foram iniciados os seguintes projetos no período de referência: Projetos Ressocializa e (Re)Integro, Formulário de Inspeção Prisional (FIP) e o Cadastro Nacional de Participação Social na Execução Penal.

As ações da Onasp são relatadas no [capítulo @sec-acoes]. Tais ações visam: fomentar e apoiar a implantação e o funcionamento de ouvidorias externas e independentes de administração da execução penal nas unidades da federação; melhorar as condições e alcance dos trabalhos da ouvidoria; e atuar como instância de controle, fiscalização e participação social. Dessa forma, foram realizados: O primeiro Fórum Nacional de Participação e Controle na Execução Penal; Inspeções em 91 unidades penitenciárias; Internalização do Serviço de Informação ao Cidadão (SIC); Restruturação organizacional da Ouvidoria Nacional dos Serviços Penais; Modernização dos equipamentos da ouvidoria; e ações de práticas restaurativas.

A última grande área de atuação da Onasp está apresentada na divisão do relatório que trata do tratamento estatístico das demandas ([capítulo @sec-estatisticas-anuais], [capítulo @sec-dados-ouvidoria-2020], [capítulo @sec-dados-ouvidoria-2021] e [capítulo @sec-dados-ouvidoria-2022]). São detalhados as formas de captação, tratamento e resposta das demandas recebidas pelos usuários e colaboradores do sistema penitenciário, além de, estatísticas sobre as demandas de ouvidoria. Todas as análises são referenciadas pela data de início do tratamento da manifestação pela Onasp. Essas informações ajudam na atuação como instância de controle e participação social responsável pelo tratamento das solicitações, reclamações, denúncias, sugestões e elogios relativos às políticas e aos serviços públicos prestados por servidores e órgãos de administração da execução penal.

Por último, no quarto capítulo, o texto traz considerações acerca de gestão penitenciária e sugere formas de garantir os direitos das pessoas privadas de liberdade e seus familiares baseado nas experiências com os projetos em andamento e nas informações estatísticas coletadas.
